# Generated by Django 2.2.4 on 2019-09-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190921_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinfo',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
